### ISSUE TITLE
On invalid auth v0.3.0, gets stuck in a loop

### ISSUE THREAD

**Issue by achew22** [hashicorp/terraform-provider-kubernetes-alpha#159]
### Terraform, Provider, Kubernetes versions

Terraform versions:
```
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.2
+ provider registry.terraform.io/hashicorp/kubernetes-alpha v0.3.0
```
Kubernetes versions:
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-gke.300", GitCommit:"a6af8499b881b1020b39e0c5f3045207f8340c46", GitTreeState:"clean", BuildDate:"2021-02-20T01:41:46Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

```

### Affected Resource(s)

This affects all of the resources in my config

### Terraform Configuration Files
```hcl
provider "kubernetes-alpha" {
  host             = "https://${var.cluster_endpoint}"

  token = data.google_client_config.default.access_token
  cluster_ca_certificate = var.cluster_ca_certificate
}
```

### Trace Output

```
2021-03-11T02:59:43.220Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 02:59:43 [DEBUG] Kubernetes API API Request Details:
2021-03-11T02:59:43.220Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ REQUEST ]---------------------------------------
2021-03-11T02:59:43.220Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: GET /api?timeout=32s HTTP/1.1
2021-03-11T02:59:43.220Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Host: 35.239.49.54
2021-03-11T02:59:43.220Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: User-Agent: terraform-provider-kubernetes-alpha_v0.3.0_x5/v0.0.0 (linux/amd64) kubernetes/$Format
2021-03-11T02:59:43.220Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept: application/json, */*
2021-03-11T02:59:43.220Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept-Encoding: gzip
2021-03-11T02:59:43.220Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T02:59:43.220Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T02:59:43.220Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 02:59:43 [DEBUG] Kubernetes API API Response Details:
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ RESPONSE ]--------------------------------------
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: HTTP/2.0 403 Forbidden
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Length: 188
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Audit-Id: 5f3a7098-9c23-4064-a6a0-e0407337e677
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Cache-Control: no-cache, private
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Type: application/json
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Date: Thu, 11 Mar 2021 02:59:43 GMT
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: X-Content-Type-Options: nosniff
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: {
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "kind": "Status",
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "apiVersion": "v1",
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "metadata": {},
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "status": "Failure",
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "message": "forbidden: User \"system:anonymous\" cannot get path \"/api\"",
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "reason": "Forbidden",
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "details": {},
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "code": 403
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: }
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T02:59:43.222Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
^C2021-03-11T02:59:43.256Z [TRACE] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: plugin received interrupt signal, ignoring: count=22 timestamp=2021-03-11T02:59:43.256Z
^C2021-03-11T02:59:43.283Z [TRACE] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: plugin received interrupt signal, ignoring: count=23 timestamp=2021-03-11T02:59:43.283Z
^C2021-03-11T02:59:43.325Z [TRACE] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: plugin received interrupt signal, ignoring: count=24 timestamp=2021-03-11T02:59:43.324Z
^C2021-03-11T02:59:43.351Z [TRACE] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: plugin received interrupt signal, ignoring: count=25 timestamp=2021-03-11T02:59:43.350Z
^C2021-03-11T02:59:43.394Z [TRACE] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: plugin received interrupt signal, ignoring: count=26 timestamp=2021-03-11T02:59:43.394Z
^C2021-03-11T02:59:43.418Z [TRACE] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: plugin received interrupt signal, ignoring: count=27 timestamp=2021-03-11T02:59:43.418Z
2021-03-11T02:59:43.420Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 02:59:43 [DEBUG] Kubernetes API API Request Details:
2021-03-11T02:59:43.420Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ REQUEST ]---------------------------------------
2021-03-11T02:59:43.420Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: GET /apis?timeout=32s HTTP/1.1
2021-03-11T02:59:43.420Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Host: 35.239.49.54
2021-03-11T02:59:43.420Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: User-Agent: terraform-provider-kubernetes-alpha_v0.3.0_x5/v0.0.0 (linux/amd64) kubernetes/$Format
2021-03-11T02:59:43.420Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept: application/json, */*
2021-03-11T02:59:43.420Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept-Encoding: gzip
2021-03-11T02:59:43.420Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T02:59:43.420Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T02:59:43.420Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 02:59:43 [DEBUG] Kubernetes API API Response Details:
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ RESPONSE ]--------------------------------------
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: HTTP/2.0 403 Forbidden
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Length: 189
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Audit-Id: 7a3f60a3-e8c7-484c-9276-7a44fe2e0ade
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Cache-Control: no-cache, private
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Type: application/json
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Date: Thu, 11 Mar 2021 02:59:43 GMT
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: X-Content-Type-Options: nosniff
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: {
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "kind": "Status",
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "apiVersion": "v1",
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "metadata": {},
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "status": "Failure",
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "message": "forbidden: User \"system:anonymous\" cannot get path \"/apis\"",
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "reason": "Forbidden",
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "details": {},
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "code": 403
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: }
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T02:59:43.422Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
```

Then it prints that in a loop indefinitely.

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

What should have happened?

It should have failed after some reasonable number of retries and informed the user that auth was broken.

### Actual Behavior

What actually happened?

It looped indefinitely

### Important Factoids

Not to my knowledge, but happy to add more if you have questions.

### References

None.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by achew22** [comment]
Oops! I guess I snagged a section of the scrollback that has me manically hitting `ctrl-c`, but I assure you that I could have scrolled back another 1000 lines and gotten approximately the same output.

**Comment by achew22** [comment]
I just tried it using cert based logins and got the same result.

```hcl
provider "kubernetes-alpha" {
  host = "https://${var.cluster_endpoint}"

  client_certificate     = base64decode(var.client_certificate)
  client_key             = base64decode(var.client_key)
  cluster_ca_certificate = var.cluster_ca_certificate
}
```

Output:

```
2021-03-11T03:18:58.538Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 03:18:58 [DEBUG] Kubernetes API API Response Details:
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ RESPONSE ]--------------------------------------
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: HTTP/2.0 403 Forbidden
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Length: 188
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Audit-Id: 573e4b4e-a14d-4a1a-8baf-fa28d2a52f25
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Cache-Control: no-cache, private
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Type: application/json
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Date: Thu, 11 Mar 2021 03:18:58 GMT
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: X-Content-Type-Options: nosniff
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: {
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "kind": "Status",
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "apiVersion": "v1",
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "metadata": {},
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "status": "Failure",
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "message": "forbidden: User \"system:anonymous\" cannot get path \"/api\"",
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "reason": "Forbidden",
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "details": {},
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "code": 403
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: }
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T03:18:58.540Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
2021-03-11T03:18:58.737Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 03:18:58 [DEBUG] Kubernetes API API Request Details:
2021-03-11T03:18:58.737Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ REQUEST ]---------------------------------------
2021-03-11T03:18:58.737Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: GET /apis?timeout=32s HTTP/1.1
2021-03-11T03:18:58.737Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Host: 35.239.49.54
2021-03-11T03:18:58.737Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: User-Agent: terraform-provider-kubernetes-alpha_v0.3.0_x5/v0.0.0 (linux/amd64) kubernetes/$Format
2021-03-11T03:18:58.737Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept: application/json, */*
2021-03-11T03:18:58.737Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept-Encoding: gzip
2021-03-11T03:18:58.737Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T03:18:58.737Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T03:18:58.737Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 03:18:58 [DEBUG] Kubernetes API API Response Details:
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ RESPONSE ]--------------------------------------
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: HTTP/2.0 403 Forbidden
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Length: 189
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Audit-Id: a2d3d7f8-43e6-413a-9809-0a6d4397ddb6
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Cache-Control: no-cache, private
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Type: application/json
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Date: Thu, 11 Mar 2021 03:18:58 GMT
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: X-Content-Type-Options: nosniff
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: {
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "kind": "Status",
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "apiVersion": "v1",
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "metadata": {},
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "status": "Failure",
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "message": "forbidden: User \"system:anonymous\" cannot get path \"/apis\"",
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "reason": "Forbidden",
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "details": {},
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "code": 403
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: }
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T03:18:58.739Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
2021-03-11T03:18:58.740Z [TRACE] plugin.stdio: received data: channel=STDERR len=97
2021-03-11T03:18:58.740Z [TRACE] plugin.stdio: waiting for stdio data
2021-03-11T03:18:58.937Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 03:18:58 [DEBUG] Kubernetes API API Request Details:
2021-03-11T03:18:58.938Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ REQUEST ]---------------------------------------
2021-03-11T03:18:58.938Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: GET /api?timeout=32s HTTP/1.1
2021-03-11T03:18:58.938Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Host: 35.239.49.54
2021-03-11T03:18:58.938Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: User-Agent: terraform-provider-kubernetes-alpha_v0.3.0_x5/v0.0.0 (linux/amd64) kubernetes/$Format
2021-03-11T03:18:58.938Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept: application/json, */*
2021-03-11T03:18:58.938Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept-Encoding: gzip
2021-03-11T03:18:58.938Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T03:18:58.938Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T03:18:58.938Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 03:18:58 [DEBUG] Kubernetes API API Response Details:
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ RESPONSE ]--------------------------------------
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: HTTP/2.0 403 Forbidden
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Length: 188
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Audit-Id: 72369431-a80b-4f2c-b9f0-77514e1de070
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Cache-Control: no-cache, private
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Type: application/json
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Date: Thu, 11 Mar 2021 03:18:58 GMT
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: X-Content-Type-Options: nosniff
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: {
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "kind": "Status",
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "apiVersion": "v1",
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "metadata": {},
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "status": "Failure",
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "message": "forbidden: User \"system:anonymous\" cannot get path \"/api\"",
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "reason": "Forbidden",
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "details": {},
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "code": 403
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: }
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T03:18:58.939Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
2021-03-11T03:18:59.137Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 03:18:59 [DEBUG] Kubernetes API API Request Details:
2021-03-11T03:18:59.137Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ REQUEST ]---------------------------------------
2021-03-11T03:18:59.137Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: GET /apis?timeout=32s HTTP/1.1
2021-03-11T03:18:59.137Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Host: 35.239.49.54
2021-03-11T03:18:59.137Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: User-Agent: terraform-provider-kubernetes-alpha_v0.3.0_x5/v0.0.0 (linux/amd64) kubernetes/$Format
2021-03-11T03:18:59.137Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept: application/json, */*
2021-03-11T03:18:59.137Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept-Encoding: gzip
2021-03-11T03:18:59.137Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T03:18:59.137Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T03:18:59.137Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 03:18:59 [DEBUG] Kubernetes API API Response Details:
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ RESPONSE ]--------------------------------------
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: HTTP/2.0 403 Forbidden
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Length: 189
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Audit-Id: dbe3c0d7-cbce-467c-b626-b16e26036e23
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Cache-Control: no-cache, private
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Type: application/json
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Date: Thu, 11 Mar 2021 03:18:59 GMT
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: X-Content-Type-Options: nosniff
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: {
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "kind": "Status",
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "apiVersion": "v1",
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "metadata": {},
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "status": "Failure",
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "message": "forbidden: User \"system:anonymous\" cannot get path \"/apis\"",
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "reason": "Forbidden",
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "details": {},
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "code": 403
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: }
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T03:18:59.139Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
2021-03-11T03:18:59.140Z [TRACE] plugin.stdio: received data: channel=STDERR len=97
2021-03-11T03:18:59.140Z [TRACE] plugin.stdio: waiting for stdio data
```

**Comment by aareet** [comment]
Hi, v0.3.0 requires 0.14.8 or above because it relies on a fix in that version

**Comment by achew22** [comment]
Hey @aareet, thanks for the quick response.

I just ran this again with 0.14.8.

```
$ terraform version && TF_LOG=trace terraform apply
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.2
+ provider registry.terraform.io/hashicorp/kubernetes-alpha v0.3.0

... many many lines of log later...

2021-03-11T06:28:43.917Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 06:28:43 [DEBUG] Kubernetes API API Request Details:
2021-03-11T06:28:43.917Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ REQUEST ]---------------------------------------
2021-03-11T06:28:43.917Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: GET /api?timeout=32s HTTP/1.1
2021-03-11T06:28:43.917Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Host: 34.72.85.127
2021-03-11T06:28:43.917Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: User-Agent: terraform-provider-kubernetes-alpha_v0.3.0_x5/v0.0.0 (linux/amd64) kubernetes/$Format
2021-03-11T06:28:43.917Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept: application/json, */*
2021-03-11T06:28:43.917Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept-Encoding: gzip
2021-03-11T06:28:43.917Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T06:28:43.917Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T06:28:43.917Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 06:28:43 [DEBUG] Kubernetes API API Response Details:
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ RESPONSE ]--------------------------------------
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: HTTP/2.0 403 Forbidden
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Length: 188
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Audit-Id: 5139906b-4707-4bd3-b7f8-32ba4d4f20af
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Cache-Control: no-cache, private
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Type: application/json
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Date: Thu, 11 Mar 2021 06:28:43 GMT
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: X-Content-Type-Options: nosniff
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: {
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "kind": "Status",
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "apiVersion": "v1",
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "metadata": {},
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "status": "Failure",
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "message": "forbidden: User \"system:anonymous\" cannot get path \"/api\"",
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "reason": "Forbidden",
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "details": {},
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "code": 403
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: }
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T06:28:43.919Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
2021-03-11T06:28:44.117Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 06:28:44 [DEBUG] Kubernetes API API Request Details:
2021-03-11T06:28:44.117Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ REQUEST ]---------------------------------------
2021-03-11T06:28:44.117Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: GET /apis?timeout=32s HTTP/1.1
2021-03-11T06:28:44.117Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Host: 34.72.85.127
2021-03-11T06:28:44.117Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: User-Agent: terraform-provider-kubernetes-alpha_v0.3.0_x5/v0.0.0 (linux/amd64) kubernetes/$Format
2021-03-11T06:28:44.117Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept: application/json, */*
2021-03-11T06:28:44.117Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept-Encoding: gzip
2021-03-11T06:28:44.117Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T06:28:44.117Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T06:28:44.117Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 06:28:44 [DEBUG] Kubernetes API API Response Details:
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ RESPONSE ]--------------------------------------
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: HTTP/2.0 403 Forbidden
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Length: 189
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Audit-Id: 40157447-f174-454d-8f5e-0ff3ceccac7e
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Cache-Control: no-cache, private
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Type: application/json
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Date: Thu, 11 Mar 2021 06:28:44 GMT
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: X-Content-Type-Options: nosniff
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: {
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "kind": "Status",
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "apiVersion": "v1",
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "metadata": {},
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "status": "Failure",
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "message": "forbidden: User \"system:anonymous\" cannot get path \"/apis\"",
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "reason": "Forbidden",
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "details": {},
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "code": 403
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: }
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T06:28:44.119Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
2021-03-11T06:28:44.119Z [TRACE] plugin.stdio: received data: channel=STDERR len=97
2021-03-11T06:28:44.119Z [TRACE] plugin.stdio: waiting for stdio data
2021-03-11T06:28:44.317Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 06:28:44 [DEBUG] Kubernetes API API Request Details:
2021-03-11T06:28:44.317Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ REQUEST ]---------------------------------------
2021-03-11T06:28:44.317Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: GET /api?timeout=32s HTTP/1.1
2021-03-11T06:28:44.317Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Host: 34.72.85.127
2021-03-11T06:28:44.317Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: User-Agent: terraform-provider-kubernetes-alpha_v0.3.0_x5/v0.0.0 (linux/amd64) kubernetes/$Format
2021-03-11T06:28:44.317Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept: application/json, */*
2021-03-11T06:28:44.317Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept-Encoding: gzip
2021-03-11T06:28:44.317Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T06:28:44.317Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T06:28:44.317Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
2021-03-11T06:28:44.318Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 06:28:44 [DEBUG] Kubernetes API API Response Details:
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ RESPONSE ]--------------------------------------
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: HTTP/2.0 403 Forbidden
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Length: 188
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Audit-Id: 9d8ae321-75c9-4542-a39a-0b851059a790
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Cache-Control: no-cache, private
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Type: application/json
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Date: Thu, 11 Mar 2021 06:28:44 GMT
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: X-Content-Type-Options: nosniff
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: {
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "kind": "Status",
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "apiVersion": "v1",
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "metadata": {},
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "status": "Failure",
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "message": "forbidden: User \"system:anonymous\" cannot get path \"/api\"",
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "reason": "Forbidden",
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "details": {},
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "code": 403
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: }
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T06:28:44.319Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
2021-03-11T06:28:44.517Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 06:28:44 [DEBUG] Kubernetes API API Request Details:
2021-03-11T06:28:44.517Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ REQUEST ]---------------------------------------
2021-03-11T06:28:44.517Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: GET /apis?timeout=32s HTTP/1.1
2021-03-11T06:28:44.517Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Host: 34.72.85.127
2021-03-11T06:28:44.517Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: User-Agent: terraform-provider-kubernetes-alpha_v0.3.0_x5/v0.0.0 (linux/amd64) kubernetes/$Format
2021-03-11T06:28:44.517Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept: application/json, */*
2021-03-11T06:28:44.517Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept-Encoding: gzip
2021-03-11T06:28:44.517Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T06:28:44.517Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T06:28:44.517Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: 2021/03/11 06:28:44 [DEBUG] Kubernetes API API Response Details:
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ RESPONSE ]--------------------------------------
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: HTTP/2.0 403 Forbidden
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Length: 189
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Audit-Id: e1a45528-5206-4354-9d63-e047e40f3c46
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Cache-Control: no-cache, private
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Content-Type: application/json
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Date: Thu, 11 Mar 2021 06:28:44 GMT
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: X-Content-Type-Options: nosniff
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: {
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "kind": "Status",
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "apiVersion": "v1",
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "metadata": {},
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "status": "Failure",
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "message": "forbidden: User \"system:anonymous\" cannot get path \"/apis\"",
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "reason": "Forbidden",
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "details": {},
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:  "code": 403
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: }
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5:
2021-03-11T06:28:44.519Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: -----------------------------------------------------
```

Then it repeats indefinitely.

```sh
$ sha256sum $(which terraform)
0370f001ec37d6a6d71bd63ac3c5b0e7131c7885419b973b0955193580111324  /home/achew22/.bin/terraform
```

If you'd like to confirm that I'm at the exact same build. I pulled it with:

```sh
$ wget https://releases.hashicorp.com/terraform/0.14.8/terraform_0.14.8_linux_amd64.zip
```

**Comment by aareet** [comment]
Thanks for trying this out with the latest - we'll take a look and try to reproduce/fix

**Comment by jbg** [comment]
@achew22 Did you figure out the underlying auth issue that triggered this bug? We have the same issue (with the same "stuck in a loop" end result) and we are trying to trace the auth issue - `kubernetes-alpha` is being set up the same way as the `kubernetes` provider which is working fine, but `kubernetes-alpha` is looping with the same error you got: `User "system:anonymous" cannot get path "/apis"`

**Comment by achew22** [comment]
@jbg could you comment on https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/162 with any additional context you have on the auth error?

**Comment by achew22** [comment]
Specifically, I'm curious if this is a GKE only thing or if it is happening with other flavors of Kubernetes

**Comment by jbg** [comment]
Done. Notably, I'm on AWS EKS and not GKE.

**Comment by mentos1386** [comment]
@achew22 I'm also having similar issue using AWS EKS. This is the first time i tried to use it, so i can't say if it worked on `0.2.x`.

I'm trying to use `kubernetes-alpha` in the same way as i would `kubernetes` provider.
```tf
provider "kubernetes-alpha" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
}
```

**Comment by marcuz** [comment]
> @achew22 I'm also having similar issue using AWS EKS. This is the first time i tried to use it, so i can't say if it worked on `0.2.x`.
> 
> I'm trying to use `kubernetes-alpha` in the same way as i am using `kubernetes` provider.
> 
> ```terraform
> provider "kubernetes-alpha" {
>   host                   = data.aws_eks_cluster.cluster.endpoint
>   cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
>   token                  = data.aws_eks_cluster_auth.cluster.token
> }
> ```
Same here, AWS EKS and I confirm it worked on `0.2.1`, but not `0.3.0`.

**Comment by alexsomesan** [comment]
v0.3.1 is now out and should include the fix for this.
Can you please try it out and confirm whether the issue is still present or not?

**Comment by achew22** [comment]
I believe this issue tracks a different concern than was addressed by #163. #163 tracks sending the incorrect auth token, but I believe this bug tracks the fact that it hangs indefinitely because it attempts to login repeatedly and doesn't have a stopping condition.

Obviously, feel free to ignore me on this one, but I think this is a functionally different issue.

**Comment by davidalger** [comment]
I can confirm this issue continues to persist. With either of the following provider configurations, it still gets stuck in a loop:

```
provider "kubernetes-alpha" {
  host                   = "https://${data.terraform_remote_state.cluster.outputs.gke.endpoint}"
  token                  = "bogus-token"
  cluster_ca_certificate = data.terraform_remote_state.cluster.outputs.gke.cluster_ca_certificate
}
```
or
```
provider "kubernetes-alpha" {
  host                   = "https://${data.terraform_remote_state.cluster.outputs.gke.endpoint}"
  cluster_ca_certificate = data.terraform_remote_state.cluster.outputs.gke.cluster_ca_certificate
}
```

Result being endless entries like this (from `TF_LOG=trace terraform plan`):
```
2021-03-11T16:26:58.899-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: 2021/03/11 16:26:58 [DEBUG] Kubernetes API API Request Details:
2021-03-11T16:26:58.899-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: ---[ REQUEST ]---------------------------------------
2021-03-11T16:26:58.899-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: GET /api?timeout=32s HTTP/1.1
2021-03-11T16:26:58.899-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: Host: 35.232.38.233
2021-03-11T16:26:58.899-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: User-Agent: terraform-provider-kubernetes-alpha_v0.3.1_x5/v0.0.0 (darwin/amd64) kubernetes/$Format
2021-03-11T16:26:58.899-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: Accept: application/json, */*
2021-03-11T16:26:58.899-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: Authorization: Bearer bogus-token
2021-03-11T16:26:58.899-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: Accept-Encoding: gzip
2021-03-11T16:26:58.899-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: 
2021-03-11T16:26:58.899-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: 
2021-03-11T16:26:58.899-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: -----------------------------------------------------
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: 2021/03/11 16:26:59 [DEBUG] Kubernetes API API Response Details:
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: ---[ RESPONSE ]--------------------------------------
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: HTTP/2.0 401 Unauthorized
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: Content-Length: 129
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: Audit-Id: 3d4294d1-fd32-4e42-9052-f77780eb5d5b
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: Cache-Control: no-cache, private
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: Content-Type: application/json
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: Date: Thu, 11 Mar 2021 22:26:59 GMT
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: 
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: {
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5:  "kind": "Status",
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5:  "apiVersion": "v1",
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5:  "metadata": {},
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5:  "status": "Failure",
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5:  "message": "Unauthorized",
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5:  "reason": "Unauthorized",
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5:  "code": 401
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: }
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: 
2021-03-11T16:26:59.192-0600 [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.1_x5: -----------------------------------------------------
```

Giving it a valid token however now works as expected:
```
provider "kubernetes-alpha" {
  host                   = "https://${data.terraform_remote_state.cluster.outputs.gke.endpoint}"
  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = data.terraform_remote_state.cluster.outputs.gke.cluster_ca_certificate
}
```

**Comment by davidalger** [comment]
_Slight correction to my previous comment._

If I specify an invalid token, it does timeout as one would expect:
```
provider "kubernetes-alpha" {
  host                   = "https://${data.terraform_remote_state.cluster.outputs.gke.endpoint}"
  token                  = "bogus-token"
  cluster_ca_certificate = data.terraform_remote_state.cluster.outputs.gke.cluster_ca_certificate
}
```

```
$ time terraform plan
helm_release.traefik: Refreshing state... [id=traefik]
kubernetes_manifest.traefik_backend_config: Refreshing state...

Error: rpc error: code = Unknown desc = Unauthorized



real	0m11.563s
user	0m5.625s
sys	0m1.341s
```

Omit the token completely and the loop still occurs (you can see I cancelled it after waiting over 6 minutes):

```
provider "kubernetes-alpha" {
  host                   = "https://${data.terraform_remote_state.cluster.outputs.gke.endpoint}"
  cluster_ca_certificate = data.terraform_remote_state.cluster.outputs.gke.cluster_ca_certificate
}
```

```
$ time terraform plan
helm_release.traefik: Refreshing state... [id=traefik]
kubernetes_manifest.traefik_backend_config: Refreshing state...
^CInterrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...
Stopping operation...
^CTwo interrupts received. Exiting immediately. Note that data
loss may have occurred.
Releasing state lock. This may take a few moments...

Error: operation canceled



real	6m16.573s
user	0m8.040s
sys	0m3.877s
```

**Comment by alexsomesan** [comment]
Thanks for letting me know this is still happening. I wasn't able to reproduce it after I fixed the token issue.
I'll try with this new configuration that you just shared.

Would you mind also sharing a complete trace log (doesn't matter if you stop the provider with ctrl-c, the messages I'm interested should already be there).

**Comment by davidalger** [comment]
Provider config
```
provider "kubernetes-alpha" {
  host                   = "https://${data.terraform_remote_state.cluster.outputs.gke.endpoint}"
  cluster_ca_certificate = data.terraform_remote_state.cluster.outputs.gke.cluster_ca_certificate
}
```

Resulting trace:
[provider-trace.log](https://github.com/hashicorp/terraform-provider-kubernetes-alpha/files/6126448/provider-trace.log)

**Comment by alexsomesan** [comment]
Thanks! 
I can now reproduce it too, but only if token is omitted completely. 
If it's set to a wrong value I don't get the retries.

**Comment by alexsomesan** [comment]
I was able to trace this back to a potential bug in the cached RESTMapper interface in client-go.
Looking for solutions.
