### ISSUE TITLE
Metric Server APIService Provisioning fails

### ISSUE THREAD

**Issue by gangadharayya-hiremath-tm** [hashicorp/terraform-provider-kubernetes-alpha#209]
Terraform version:0.15.3
Provider version:kubernetes-alpha
Kubernetes version:1.19

### Affected Resource(s)
Metric Server API service Provisioning fails with error:
Error: PATCH for resource "/v1beta1.metrics.k8s.io" failed to apply
Patch
│ "https://<**placeholder**>.gr7.us-west-2.eks.amazonaws.com/apis/apiregistration.k8s.io/v1/apiservices/v1beta1.metrics.k8s.io?fieldManager=Terraform":
│ stream error: stream ID 83; INTERNAL_ERROR

### Terraform Configuration Files
resource "kubernetes_manifest" "metric-sever-api-service" {
 provider = kubernetes-alpha
 manifest = {
  "apiVersion" = "apiregistration.k8s.io/v1"
  "kind" = "APIService"
  "metadata" = {
    "labels" = {
      "k8s-app" = "metrics-server"
    }
    "name" = "v1beta1.metrics.k8s.io"
  }
  "spec" = {
    "group" = "metrics.k8s.io"
    "groupPriorityMinimum" = 100
    "insecureSkipTLSVerify" = true
    "service" = {
      "name" = "metrics-server"
      "namespace" = "kube-system"
    }
    "version" = "v1beta1"
    "versionPriority" = 100
  }
}

### Panic Output
Error: PATCH for resource "/v1beta1.metrics.k8s.io" failed to apply
Patch
│ "https://<**placeholder**>.gr7.us-west-2.eks.amazonaws.com/apis/apiregistration.k8s.io/v1/apiservices/v1beta1.metrics.k8s.io?fieldManager=Terraform":
│ stream error: stream ID 83; INTERNAL_ERROR

### Steps to Reproduce

1. Convert yaml to create metric server service using "echo 'yamldecode(file("test.yaml"))' | terraform console"
2. terraform apply will result in error as detailed above

### Expected Behavior
What should have happened?
1. Metric Server API service should have got provisioned

### Actual Behavior
What actually happened?

### Important Factoids
When attempted to apply yaml file directly, it works fine - fails consistently when tried through terraform Kubernetes-alpha provider

When applied directly using yaml file as following, it works fine

apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    k8s-app: metrics-server
  name: v1beta1.metrics.k8s.io
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: metrics-server
    namespace: kube-system
  version: v1beta1
  versionPriority: 100
~                      

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by AlKapkone** [comment]
I have the same issue! Please, fix it!

**Comment by gordonbondon** [comment]
Looks related to kubernetes/kubernetes#89264, probably fixed in kubernetes/kubernetes#98576

**Comment by AlKapkone** [comment]
Looks the same as in https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/204.
So I'm using AWS EKS **v1.20.4-eks-6b7464** and based on Alex's reply it's unfortunately not fixed in mu current version of K8s.
